[package]
name = "mousemode"
version = "0.1.0"
authors = ["'ghsable' <'suna@xmpp.is'>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device_query = "0.2.8"
mouse-rs = "0.4"
